sudo: required
language: python
python:
  - '2.7'
install:
  - git remote -v
  - git ls-remote --heads origin
before_install:
  - openssl aes-256-cbc -K $encrypted_bbd230db0088_key -iv $encrypted_bbd230db0088_iv -in github_deploy_key.enc -out /tmp/github_deploy_key -d
  - chmod 600 /tmp/github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add /tmp/github_deploy_key
script:
  - |
    v=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
    echo "[stable] $v"
    tags=$(git ls-remote --tags https://github.com/kubernetes/kubernetes.git | grep 'v[1-9]\.[0-9]*\.[0-9]*$' | awk -F'tags/' '{print $2}' | sort -t. -k1,1n -k2,2n -k3,3n | sed -n '{/\.0$/{g;p}};h')
    tags="$tags $v"
    echo "[tags] $tags"
    for t in $tags;do
      echo "[check] $t"
      b=$(git ls-remote --heads origin | awk -F'heads/' '{print $2}' | grep -w ${t} | wc -l)
      if [[ $b == 0 ]]; then
        echo "[push] $t"
        git config --global user.email "lework@yeah.net"
        git config --global user.name "lework"
        git remote rm origin
        git remote add origin git@github.com:lework/Docker-kubectl.git
        git pull
        git checkout -b $t
        sed -i "s/\\(K8S_VERSION=\\).*/\\1$t/g" Dockerfile
        sed -i "/| scratch |/a\\| $t | $t | $t | alpine 3.9 |" README.md
        git add -A
        git commit -m "add $t"
        git push -u origin $t
        if [[ "$t" == "$v" ]]; then
          git checkout master
          git merge $t
          git push origin master
        fi
      fi
    done
